services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "5681:5672/tcp"
      - "15681:15672/tcp"
    environment:
      RABBITMQ_ERLANG_COOKIE: "somesecretcookie"
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5460:5432"
    environment:
      POSTGRES_USER: games
      POSTGRES_PASSWORD: games
      POSTGRES_DB: games

  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    ports:
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes